version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gestionprojets
    ports:
      - "3307:3306"

  backend:
    build: ./gestionprojects
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./gestion-projects-frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend