version: '3.8'

services:
  mysql:
    image: mysql:8.2
    container_name: mysql_gestionprojets
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gestionprojets
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./gestionprojets
      dockerfile: Dockerfile
    container_name: api_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestionprojets?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      TZ: Europe/Brussels
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./gestion-projets-frontend
      dockerfile: Dockerfile
    container_name: web_frontend
    environment:
      VITE_API_TARGET: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "5174:5174"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_gestionprojets
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
