ALTER TABLE projets
    MODIFY statut ENUM('ACTIF','SUSPENDU','TERMINE','ANNULE')
    NOT NULL DEFAULT 'ACTIF';

ALTER TABLE messages
    MODIFY type ENUM('TEXT','SYSTEM','NOTIFICATION') DEFAULT 'TEXT',
    MODIFY statut ENUM('ENVOYE','DELIVRE','LU') DEFAULT 'ENVOYE';
