INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('hebertdiane@bernier.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('perrotfrancois@ifrance.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('charlesnoel@noos.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lefebvrejosette@sfr.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('samsoncatherine@lefort.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('andremarie@bouygtel.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('charlottebrunet@laposte.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('zoelemaire@noos.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('rmarchal@guillaume.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('fgermain@voila.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('couturiercelina@dbmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('marinepottier@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('andree60@gallet.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('laure08@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('pvaillant@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('chretiencorinne@gmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('constancelamy@barthelemy.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('ovasseur@peron.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('margaret27@vidal.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('maurice06@jacquot.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('frederic85@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('emile83@robin.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lucielevy@tiscali.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('alexdelattre@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('marcbarthelemy@laposte.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('albertadrien@tele2.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('ibriand@coulon.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('mauryadrien@bouygtel.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('genevieve67@pages.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('jeromegay@faure.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('emmanuelmary@hotmail.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('wleclercq@le.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('dianemichel@martins.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('zoebourdon@fischer.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('ivalette@tiscali.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('jeannineparent@gmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('delahayethomas@perrier.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('odettelebrun@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('ijacquot@tele2.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('bertrand41@masse.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('kpetit@laposte.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('andrealice@begue.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('denisbenoit@lopez.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('marguerite15@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('celinamasson@julien.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('hlaunay@chevallier.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('augustinnoel@tele2.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lecoqcharlotte@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('hugues72@legendre.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('blanchetjuliette@guyot.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('pereiradenise@da.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('dparent@free.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('jroussel@hotmail.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('aurelieclerc@gosselin.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('margot08@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('georgesbrunet@live.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('couturierdenis@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('camussabine@laposte.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('robertchauveau@perrot.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('zleclerc@da.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('pgrenier@ifrance.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('patrickle-roux@joseph.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('marceljacques@bouygtel.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('da-costaeleonore@sfr.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('massonmichele@free.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('bbaron@fernandes.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('jacquotlorraine@jacquot.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('xpoirier@pierre.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('adriennediallo@renaud.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lorrainebaron@ifrance.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('marinepoirier@vincent.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('maryse86@couturier.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('margauxgilbert@orange.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('mrousset@jacquot.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('uregnier@garcia.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('gregoire63@texier.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('sebastienandre@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('annejacquet@yahoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('patrickbaudry@gmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lebrunaurelie@orange.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('etiennecouturier@hotmail.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('pclement@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('delahayemarc@club-internet.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('oceane30@roger.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('gillesjoubert@vidal.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('louisvalerie@free.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('michele68@wanadoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('oleclercq@live.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('juliette18@yahoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('colinbenoit@bouygtel.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('roberthebert@yahoo.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('andrehubert@live.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('gcarpentier@noos.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Membre', 'en', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('maringuy@laposte.net', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('acolin@jacquet.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('ledouxjean@gros.org', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('christinelacroix@allain.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('mcousin@gmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('lefortemmanuel@dbmail.com', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Chef de projet', 'fr', 1);
INSERT INTO utilisateurs (email, mot_de_passe, role, langue, cgu_accepte) VALUES ('victoire11@tiscali.fr', '$2b$12$2Hr4PsENsgZfUaetaq5B5OTpiI6gxDfK.1ROv8fhSair3IoDu5/6S', 'Administrateur', 'fr', 1);