INSERT INTO projets (titre, description, id_createur, statut, date_creation) VALUES
                                                                                 ('Application Mobile E-commerce', 'Développement d''une application mobile de vente en ligne avec paiement intégré', 1, 'ACTIF', '2024-01-15 09:00:00'),
                                                                                 ('Site Web Portfolio Architecte', 'Création d''un site vitrine pour cabinet d''architecture avec galerie interactive', 2, 'ACTIF', '2024-01-20 14:30:00'),
                                                                                 ('Système de Gestion RH', 'Application web pour gestion des ressources humaines (congés, évaluations, paie)', 1, 'ACTIF', '2024-02-01 08:15:00'),
                                                                                 ('Plateforme de Formation en Ligne', 'Site d''e-learning avec vidéos, quiz et certification', 3, 'ACTIF', '2024-02-10 10:45:00'),
                                                                                 ('Application de Livraison Restaurant', 'App mobile pour commande et livraison de repas', 2, 'TERMINE', '2024-01-05 16:20:00'),
                                                                                 ('Boutique en Ligne Vêtements', 'E-commerce spécialisé mode avec essayage virtuel', 1, 'ACTIF', '2024-02-15 11:30:00'),
                                                                                 ('Gestion de Stock Pharmacie', 'Logiciel de gestion des médicaments et inventaire', 4, 'ACTIF', '2024-01-25 13:45:00'),
                                                                                 ('Réseau Social Étudiants', 'Plateforme sociale dédiée aux étudiants universitaires', 3, 'ACTIF', '2024-02-05 09:20:00'),
                                                                                 ('Application de Covoiturage', 'Service de partage de trajets avec géolocalisation', 2, 'ACTIF', '2024-01-30 15:10:00'),
                                                                                 ('Site de Réservation Hôtel', 'Plateforme de booking avec paiement en ligne', 1, 'TERMINE', '2024-01-10 12:00:00'),
                                                                                 ('CRM Immobilier', 'Gestion de la relation client pour agence immobilière', 4, 'ACTIF', '2024-02-20 08:30:00'),
                                                                                 ('Application Fitness Tracker', 'Suivi d''activité physique et nutrition', 3, 'ACTIF', '2024-01-18 14:15:00'),
                                                                                 ('Plateforme de Freelancing', 'Mise en relation freelances et clients', 2, 'ACTIF', '2024-02-08 10:20:00'),
                                                                                 ('Système de Caisse Restaurant', 'Logiciel de point de vente pour restauration', 1, 'ACTIF', '2024-01-28 16:45:00'),
                                                                                 ('Application de Méditation', 'App de bien-être avec séances guidées', 3, 'TERMINE', '2024-01-12 11:25:00'),
                                                                                 ('Gestionnaire de Tâches Équipe', 'Outil de collaboration et suivi de projets', 4, 'ACTIF', '2024-02-12 09:40:00'),
                                                                                 ('Site de Petites Annonces', 'Plateforme d''annonces locales avec messagerie', 2, 'ACTIF', '2024-01-22 13:20:00'),
                                                                                 ('Application de Quiz Éducatif', 'Jeux éducatifs pour enfants avec récompenses', 1, 'ACTIF', '2024-02-03 15:30:00'),
                                                                                 ('Plateforme de Streaming Musique', 'Service d''écoute musicale avec playlists', 3, 'ACTIF', '2024-01-17 12:10:00'),
                                                                                 ('Gestion de Cabinet Médical', 'Logiciel de rendez-vous et dossiers patients', 4, 'ACTIF', '2024-02-18 14:50:00'),
                                                                                 ('Application de Météo Locale', 'Prévisions météo hyper-locales avec alertes', 2, 'TERMINE', '2024-01-08 10:35:00'),
                                                                                 ('E-commerce Produits Bio', 'Boutique en ligne spécialisée produits biologiques', 1, 'ACTIF', '2024-02-25 11:45:00'),
                                                                                 ('Système de Vote Électronique', 'Plateforme sécurisée pour élections en ligne', 4, 'ACTIF', '2024-01-26 16:20:00'),
                                                                                 ('Application de Reconnaissance Vocale', 'Transcription automatique speech-to-text', 3, 'ACTIF', '2024-02-07 08:55:00'),
                                                                                 ('Plateforme de Crowdfunding', 'Financement participatif pour projets innovants', 2, 'ACTIF', '2024-01-19 13:40:00'),
                                                                                 ('Gestion de Flotte Véhicules', 'Suivi GPS et maintenance de véhicules d''entreprise', 1, 'ACTIF', '2024-02-14 15:25:00'),
                                                                                 ('Application de Lecture QR Code', 'Scanner QR avec historique et partage', 3, 'TERMINE', '2024-01-13 09:15:00'),
                                                                                 ('Site de Comparaison Prix', 'Comparateur automatique de prix en ligne', 4, 'ACTIF', '2024-02-21 12:30:00'),
                                                                                 ('Application de Chat Vidéo', 'Visioconférence sécurisée pour entreprises', 2, 'ACTIF', '2024-01-31 14:05:00'),
                                                                                 ('Plateforme de Microblogging', 'Réseau social de messages courts', 1, 'ACTIF', '2024-02-09 10:50:00'),
                                                                                 ('Système de Backup Cloud', 'Sauvegarde automatique de données en cloud', 3, 'ACTIF', '2024-01-24 16:35:00'),
                                                                                 ('Application de Géolocalisation', 'Service de navigation avec trafic en temps réel', 4, 'ACTIF', '2024-02-16 08:20:00'),
                                                                                 ('Plateforme de Vente aux Enchères', 'Site d''enchères en ligne avec système d''offres', 2, 'TERMINE', '2024-01-11 11:55:00'),
                                                                                 ('Gestion de Bibliothèque', 'Système de prêt et catalogage de livres', 1, 'ACTIF', '2024-02-22 13:10:00'),
                                                                                 ('Application de Calcul Scientifique', 'Calculatrice avancée pour ingénieurs', 3, 'ACTIF', '2024-01-27 15:45:00'),
                                                                                 ('Site de Réservation Spectacles', 'Billetterie en ligne pour événements culturels', 4, 'ACTIF', '2024-02-04 09:30:00'),
                                                                                 ('Application de Traduction', 'Traducteur multilingue avec reconnaissance vocale', 2, 'ACTIF', '2024-01-16 12:25:00'),
                                                                                 ('Plateforme de Gestion Énergétique', 'Monitoring consommation électrique smart home', 1, 'ACTIF', '2024-02-11 14:40:00'),
                                                                                 ('Système de Gestion Scolaire', 'Plateforme pour établissements éducatifs', 3, 'ACTIF', '2024-01-29 10:15:00'),
                                                                                 ('Application de Reconnaissance Faciale', 'Système d''authentification biométrique', 4, 'TERMINE', '2024-01-14 16:05:00'),
                                                                                 ('Site de Location Véhicules', 'Plateforme de réservation auto/moto/vélo', 2, 'ACTIF', '2024-02-17 11:20:00'),
                                                                                 ('Application de Réalité Augmentée', 'Essayage virtuel pour lunettes et montres', 1, 'ACTIF', '2024-01-21 13:35:00'),
                                                                                 ('Plateforme de Gaming Social', 'Réseau social pour joueurs avec tournois', 3, 'ACTIF', '2024-02-06 15:50:00'),
                                                                                 ('Système de Sécurité Domotique', 'Alarme connectée avec caméras IP', 4, 'ACTIF', '2024-01-23 08:45:00'),
                                                                                 ('Application de Gestion Budget', 'Suivi des finances personnelles avec graphiques', 2, 'ACTIF', '2024-02-13 12:15:00'),
                                                                                 ('Site de Journalisme Citoyen', 'Plateforme collaborative d''information locale', 1, 'TERMINE', '2024-01-09 14:30:00'),
                                                                                 ('Application de Scan Document', 'Numérisation mobile avec OCR intégré', 3, 'ACTIF', '2024-02-19 10:05:00'),
                                                                                 ('Plateforme de Télémédecine', 'Consultations médicales à distance', 4, 'ACTIF', '2024-01-31 16:25:00'),
                                                                                 ('Système de Gestion Événements', 'Organisation complète d''événements professionnels', 2, 'ACTIF', '2024-02-01 11:40:00'),
                                                                                 ('Application de Mindfulness', 'Méditation et relaxation avec suivi progrès', 1, 'ACTIF', '2024-01-15 13:55:00');

INSERT INTO projets (titre, description, id_createur, statut, date_creation) VALUES
                                                                                 ('Plateforme IoT Agriculture', 'Monitoring intelligent des cultures avec capteurs', 3, 'ACTIF', '2024-02-23 09:10:00'),
                                                                                 ('Application de Livraison Express', 'Service de coursier en moins d''une heure', 4, 'ACTIF', '2024-01-18 15:20:00'),
                                                                                 ('Site de Critique Restaurants', 'Avis et notes de restaurants avec photos', 2, 'TERMINE', '2024-01-07 12:45:00'),
                                                                                 ('Système de Parking Intelligent', 'Réservation et paiement de places de parking', 1, 'ACTIF', '2024-02-26 08:35:00'),
                                                                                 ('Application de Suivi Sommeil', 'Analyse qualité du sommeil avec conseils', 3, 'ACTIF', '2024-01-25 14:50:00'),
                                                                                 ('Plateforme de Cours Particuliers', 'Mise en relation élèves et professeurs', 4, 'ACTIF', '2024-02-15 10:25:00'),
                                                                                 ('Application de Jardinage', 'Conseils personnalisés pour plantes d''intérieur', 2, 'ACTIF', '2024-01-30 16:15:00'),
                                                                                 ('Site de Location Matériel', 'Plateforme de prêt d''outils entre particuliers', 1, 'ACTIF', '2024-02-08 11:30:00'),
                                                                                 ('Système de Gestion Chantier', 'Suivi de projets BTP avec planning équipes', 3, 'TERMINE', '2024-01-12 13:40:00'),
                                                                                 ('Application de Réservation Coiffeur', 'Booking en ligne avec rappels automatiques', 4, 'ACTIF', '2024-02-20 09:55:00'),
                                                                                 ('Plateforme de Vente Artisanat', 'Marketplace pour créateurs et artisans', 2, 'ACTIF', '2024-01-28 15:05:00'),
                                                                                 ('Application de Suivi Grossesse', 'Accompagnement personnalisé future maman', 1, 'ACTIF', '2024-02-12 12:20:00'),
                                                                                 ('Site de Généalogie', 'Recherche et construction d''arbres familiaux', 3, 'ACTIF', '2024-01-20 14:35:00'),
                                                                                 ('Système de Caisse Magasin', 'Point de vente avec gestion stock et fidélité', 4, 'ACTIF', '2024-02-27 08:50:00'),
                                                                                 ('Application de Carnet Adresses', 'Contacts intelligents avec synchronisation cloud', 2, 'TERMINE', '2024-01-06 16:40:00'),
                                                                                 ('Plateforme de Home Staging', 'Visualisation 3D aménagement intérieur', 1, 'ACTIF', '2024-02-14 11:15:00'),
                                                                                 ('Application de Suivi Médicaments', 'Rappels prise médicaments avec interactions', 3, 'ACTIF', '2024-01-26 13:25:00'),
                                                                                 ('Site de Vente Produits Locaux', 'Circuit court producteurs et consommateurs', 4, 'ACTIF', '2024-02-18 15:40:00'),
                                                                                 ('Système de Gestion Clinique Vétérinaire', 'Dossiers animaux et rendez-vous vétérinaires', 2, 'ACTIF', '2024-01-22 10:30:00'),
                                                                                 ('Application de Calcul Itinéraire', 'Navigation optimisée transports en commun', 1, 'ACTIF', '2024-02-09 12:45:00'),
                                                                                 ('Plateforme de Coaching Sportif', 'Programmes personnalisés avec suivi video', 3, 'TERMINE', '2024-01-11 14:55:00'),
                                                                                 ('Application de Gestion Caves à Vin', 'Catalogage et suivi collections vinicoles', 4, 'ACTIF', '2024-02-24 09:20:00'),
                                                                                 ('Site de Réservation Activités', 'Booking loisirs et activités touristiques', 2, 'ACTIF', '2024-01-29 16:10:00'),
                                                                                 ('Système de Vote Assemblée', 'Plateforme décisionnelle pour copropriétés', 1, 'ACTIF', '2024-02-16 11:35:00'),
                                                                                 ('Application de Contrôle Parental', 'Surveillance et limite temps écran enfants', 3, 'ACTIF', '2024-01-24 13:50:00'),
                                                                                 ('Plateforme de Troc Objets', 'Échange de biens entre particuliers', 4, 'ACTIF', '2024-02-21 08:25:00'),
                                                                                 ('Application de Suivi Allergies', 'Monitoring réactions et environnement', 2, 'TERMINE', '2024-01-08 15:15:00'),
                                                                                 ('Site de Comparaison Assurances', 'Devis automatiques assurance auto/habitation', 1, 'ACTIF', '2024-02-25 12:40:00'),
                                                                                 ('Système de Gestion Spa', 'Réservations soins et gestion planning', 3, 'ACTIF', '2024-01-19 14:05:00'),
                                                                                 ('Application de Reconnaissance Plantes', 'Identification automatique flore par photo', 4, 'ACTIF', '2024-02-11 10:50:00'),
                                                                                 ('Plateforme de Mentorat Professionnel', 'Accompagnement carrière et développement', 2, 'ACTIF', '2024-01-27 16:30:00'),
                                                                                 ('Application de Gestion Animaux', 'Carnet de santé digital pour animaux', 1, 'ACTIF', '2024-02-13 09:45:00'),
                                                                                 ('Site de Vente Instruments Musique', 'E-commerce spécialisé avec essai virtuel', 3, 'TERMINE', '2024-01-10 11:55:00'),
                                                                                 ('Système de Pointage Employés', 'Badgeuse digitale avec géofencing', 4, 'ACTIF', '2024-02-22 13:20:00'),
                                                                                 ('Application de Suivi Hydratation', 'Rappels boire eau avec objectifs personnalisés', 2, 'ACTIF', '2024-01-31 15:35:00'),
                                                                                 ('Plateforme de Financement Étudiant', 'Prêts étudiants avec garantie diplôme', 1, 'ACTIF', '2024-02-17 08:15:00'),
                                                                                 ('Application de Gestion Déchets', 'Tri sélectif intelligent avec géolocalisation', 3, 'ACTIF', '2024-01-23 12:30:00'),
                                                                                 ('Site de Réservation Terrain Sport', 'Booking courts tennis, foot, basket', 4, 'ACTIF', '2024-02-19 14:45:00'),
                                                                                 ('Système de Billetterie Concert', 'Vente tickets avec places numérotées 3D', 2, 'TERMINE', '2024-01-13 10:20:00'),
                                                                                 ('Application de Suivi Enfants', 'Localisation et sécurité enfants école', 1, 'ACTIF', '2024-02-28 16:05:00'),
                                                                                 ('Plateforme de Réparation Collaborative', 'Mise en relation réparateurs et clients', 3, 'ACTIF', '2024-01-21 11:40:00'),
                                                                                 ('Application de Gestion Équipe Sportive', 'Planning entrainements et matchs', 4, 'ACTIF', '2024-02-07 13:55:00'),
                                                                                 ('Site de Vente Livres Occasion', 'Marketplace livres d''occasion avec échange', 2, 'ACTIF', '2024-01-26 09:25:00'),
                                                                                 ('Système de Réservation Salles', 'Booking espaces événementiels avec visite 3D', 1, 'ACTIF', '2024-02-15 15:10:00'),
                                                                                 ('Application de Calcul Calories', 'Compteur calories avec base alimentaire', 3, 'TERMINE', '2024-01-09 12:35:00'),
                                                                                 ('Plateforme de Révision Examens', 'Fiches de révision collaboratives étudiants', 4, 'ACTIF', '2024-02-23 14:20:00'),
                                                                                 ('Application de Gestion Médicale', 'Dossier médical personnel sécurisé', 2, 'ACTIF', '2024-01-17 10:15:00'),
                                                                                 ('Site de Location Déguisements', 'Plateforme location costumes fêtes', 1, 'ACTIF', '2024-02-10 16:25:00'),
                                                                                 ('Système de Gestion Pressing', 'Suivi commandes nettoyage avec SMS', 3, 'ACTIF', '2024-01-28 11:50:00'),
                                                                                 ('Application de Détection Fraude', 'IA anti-fraude pour transactions bancaires', 4, 'ACTIF', '2024-02-20 13:15:00');